---
- hosts: "{{passed_in_hosts}}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: "download repo"
      command: amazon-linux-extras install epel -y
    - name: "configure repo"
      command: yum-config-manager --enable epel
    - name: "yum installation"
      yum:
        name: "{{item}}"
        state: present
      loop:
        - ansible
        - vim
    - name: "pip installation"
      pip:
        name: 
        - pipenv
        - click