---
- hosts: "{{passed_in_hosts}}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: "download repo"
      command: amazon-linux-extras install epel -y
    - name: "configure repo"
      command: yum-config-manager --enable epel
    - name: "install ansible"
      yum:
        name: ansible 
        state: present
    - name: "install wget"
      yum:
        name: wget
        state: present
    - name: "start and enable wget"
      service:
        name: wget
        state: started
        enabled: yes